[package]
name = "rustpacket"
version = "0.1.0"
authors = ["nmavis <nmavis@cisco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buf_redux = "^0.8.4" 
byteorder = "^1.3.2"
log = "^0.4.8"
failure = "0.1.6" 